services:
  postgres:
    container_name: finance-control-pg
    image: postgres
    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: finance-control-ia
      PGDATA: /data/postgres
